# Puerto del servicio de Postulaciones
server.port=8084

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:postulacionesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
