# Puerto de la aplicación
server.port=8081

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:empresasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar SQL en consola y crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración opcional de consola H2 (si quieres ver los datos desde el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# RabbitMQ (esto lo dejamos listo aunque aún no lo usemos)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=Stevz10
spring.rabbitmq.password=C@rendongo1015
cola.empresa=empresa.creada

